"""initial schema — 7 tables

Revision ID: 0946e9c41cee
Revises: 
Create Date: 2026-04-18 07:18:27.202101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0946e9c41cee'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('config_params',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sport', sa.String(length=20), nullable=False),
    sa.Column('home_team', sa.String(length=100), nullable=False),
    sa.Column('away_team', sa.String(length=100), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('espn_id', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('opening_line_home_prob', sa.Float(), nullable=True),
    sa.Column('opening_line_source', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_games_espn_id'), ['espn_id'], unique=False)

    op.create_table('insights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('data', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('home_score', sa.Integer(), nullable=True),
    sa.Column('away_score', sa.Integer(), nullable=True),
    sa.Column('period', sa.String(length=20), nullable=True),
    sa.Column('clock', sa.String(length=20), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('estimated_real_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('espn_data', sa.Text(), nullable=True),
    sa.Column('classification', sa.String(length=30), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('kalshi_price_at', sa.Integer(), nullable=True),
    sa.Column('baseline_prob', sa.Float(), nullable=True),
    sa.Column('deviation', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('game_events', schema=None) as batch_op:
        batch_op.create_index('ix_game_events_detected_at', ['detected_at'], unique=False)
        batch_op.create_index('ix_game_events_game_id', ['game_id'], unique=False)

    op.create_table('markets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('kalshi_ticker', sa.String(length=100), nullable=False),
    sa.Column('market_type', sa.String(length=50), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kalshi_ticker')
    )
    op.create_table('opening_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('home_prob', sa.Float(), nullable=False),
    sa.Column('away_prob', sa.Float(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('odds_raw', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('paper_trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_event_id', sa.Integer(), nullable=True),
    sa.Column('market_id', sa.Integer(), nullable=False),
    sa.Column('sport', sa.String(length=20), nullable=False),
    sa.Column('side', sa.String(length=10), nullable=False),
    sa.Column('entry_price', sa.Integer(), nullable=False),
    sa.Column('entry_price_adj', sa.Integer(), nullable=False),
    sa.Column('slippage_cents', sa.Integer(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('kelly_fraction', sa.Float(), nullable=True),
    sa.Column('kelly_size_cents', sa.Integer(), nullable=True),
    sa.Column('exit_price', sa.Integer(), nullable=True),
    sa.Column('pnl_cents', sa.Integer(), nullable=True),
    sa.Column('pnl_kelly_cents', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('entered_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution', sa.String(length=20), nullable=True),
    sa.Column('game_context', sa.Text(), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('skip_reason', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['game_event_id'], ['game_events.id'], ),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('paper_trades', schema=None) as batch_op:
        batch_op.create_index('ix_paper_trades_entered_at', ['entered_at'], unique=False)
        batch_op.create_index('ix_paper_trades_sport', ['sport'], unique=False)
        batch_op.create_index('ix_paper_trades_status', ['status'], unique=False)

    op.create_table('snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('market_id', sa.Integer(), nullable=False),
    sa.Column('kalshi_bid', sa.Integer(), nullable=True),
    sa.Column('kalshi_ask', sa.Integer(), nullable=True),
    sa.Column('kalshi_volume', sa.Integer(), nullable=True),
    sa.Column('bid_depth', sa.Integer(), nullable=True),
    sa.Column('ask_depth', sa.Integer(), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('snapshots', schema=None) as batch_op:
        batch_op.create_index('ix_snapshots_market_captured', ['market_id', 'captured_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('snapshots', schema=None) as batch_op:
        batch_op.drop_index('ix_snapshots_market_captured')

    op.drop_table('snapshots')
    with op.batch_alter_table('paper_trades', schema=None) as batch_op:
        batch_op.drop_index('ix_paper_trades_status')
        batch_op.drop_index('ix_paper_trades_sport')
        batch_op.drop_index('ix_paper_trades_entered_at')

    op.drop_table('paper_trades')
    op.drop_table('opening_lines')
    op.drop_table('markets')
    with op.batch_alter_table('game_events', schema=None) as batch_op:
        batch_op.drop_index('ix_game_events_game_id')
        batch_op.drop_index('ix_game_events_detected_at')

    op.drop_table('game_events')
    op.drop_table('insights')
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_games_espn_id'))

    op.drop_table('games')
    op.drop_table('config_params')
    # ### end Alembic commands ###
